_target_: cs336_basics.config.VocabConfig
name: vocab_small
inputs:
    source:
        path: data/TinyStoriesV2-GPT4-train.txt
        # hash: null
outputs:
    vocab:
        path: ${dir}/vocab.json

# input_path: ${inputs.source}
# vocab_path: ${output.source}
vocab_size: 500
special_tokens:
   - <|endoftext|>
num_workers: 4
max_chunk_size: 1000000
