defaults:
  - base_config
  - vocab: base
  - _self_

debug: ""
stage: EVAL
# the output manifest directory
dir: ${debug}runs/${stage}_${now:%Y-%m-%d_%H-%M-%S}
# the parent manifest directory
parent: None
source: None


hydra:
  run:
    dir: ${dir}
