device:
    device: cpu
    dtype: float16
model:
    vocab_size: 10000
    context_length: 16
    d_model: 64
    num_layers: 3
    num_heads: 4
    d_ff: 128
    theta: 10000
mode: "training"
optimizer:
    lr: 1e-3
source:
    dummy: 0
